/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core theme overrides mapping to CSS variables:
        "primary": "var(--primary)",
        "primary-hi": "var(--primary-hi)",
        "primary-dim": "var(--primary-dim)",
        "primary-glow": "var(--primary-glow)",
        "background": "var(--bg)",
        "bg-sidebar": "var(--bg-2)",
        "surface-card": "var(--surface)",
        "surface-container-lowest": "var(--bg-2)",
        "surface-container-low": "var(--surface-2)",
        "surface-container": "var(--surface-2)",
        "surface-container-high": "var(--surface-3)",
        "surface-container-highest": "var(--surface-3)",
        "surface": "var(--bg)",
        "surface-inner": "var(--surface-2)",
        "text-secondary": "var(--text-2)",
        "text-muted": "var(--text-3)",
        "border-subtle": "var(--border)",
        "border-medium": "var(--border-md)",
        
        "red": "var(--red)",
        "red-dim": "var(--red-dim)",
        "green": "var(--green)",
        "green-dim": "var(--green-dim)",
        "amber": "var(--amber)",
        "amber-dim": "var(--amber-dim)",
        "blue": "var(--blue)",
        "blue-dim": "var(--blue-dim)",
        "cyan": "var(--cyan)",
        "cyan-dim": "var(--cyan-dim)",
        "violet": "var(--violet)",
        "violet-dim": "var(--violet-dim)",
        "orange": "var(--orange)",
        "orange-dim": "var(--orange-dim)",
        "purple": "var(--purple)",
        "purple-dim": "var(--purple-dim)",

        "badge-paid-bg": "var(--badge-paid-bg)",
        "badge-paid-fg": "var(--badge-paid-fg)",
        "badge-due-bg": "var(--badge-due-bg)",
        "badge-due-fg": "var(--badge-due-fg)",

        // Rest of the custom colors:
        "on-tertiary": "#ffffff",
        "surface-tint": "#4d44e3",
        "primary-container": "#4f46e5",
        "surface-bright": "#f7f9fb",
        "tertiary": "#41485e",
        "on-secondary-fixed": "#07006c",
        "tertiary-container": "#586076",
        "on-error": "#ffffff",
        "on-primary-container": "#dad7ff",
        "secondary": "#4648d4",
        "on-secondary-fixed-variant": "#2f2ebe",
        "primary-fixed": "#e2dfff",
        "outline-variant": "#c7c4d8",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-variant": "#e0e3e5",
        "on-background": "var(--text-1)",
        "secondary-container": "#6063ee",
        "chart-cyan": "#0891b2",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed": "#131b2e",
        "outline": "#777587",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#d4dbf5",
        "error": "#ba1a1a",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#e1e0ff",
        "on-surface": "var(--text-1)",
        "on-surface-variant": "#464555",
        "on-error-container": "#93000a",
        "chart-violet": "#7c3aed",
        "tertiary-fixed": "#dae2fd",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#3f465c",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "24px",
        "md": "12px",
        "lg": "16px",
        "unit": "4px",
        "xs": "4px",
        "gutter": "14px",
        "xl": "24px",
        "margin-mobile": "12px",
        "sm": "8px"
      },
      fontFamily: {
        "mono-data": ["JetBrains Mono"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-bold": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-base": ["Plus Jakarta Sans"],
        "amount-hero-mobile": ["Plus Jakarta Sans"],
        "amount-hero": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "mono-data": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg": ["30px", {"lineHeight": "36px", "letterSpacing": "-0.03em", "fontWeight": "800"}],
        "body-bold": ["14px", {"lineHeight": "22px", "fontWeight": "600"}],
        "label-caps": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-base": ["14px", {"lineHeight": "22px", "fontWeight": "400"}],
        "amount-hero-mobile": ["22px", {"lineHeight": "28px", "letterSpacing": "-0.03em", "fontWeight": "800"}],
        "amount-hero": ["28px", {"lineHeight": "32px", "letterSpacing": "-0.03em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
}
